services:
  cart:
    build:
      context: .
      dockerfile: apps/cart/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - next-micro

  home:
    build:
      context: .
      dockerfile: apps/home/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://fakestoreapi.com/products}
      - CART_HOST=cart:3001
    depends_on:
      - cart
    restart: unless-stopped
    networks:
      - next-micro

networks:
  next-micro:
    driver: bridge
